# Example configuration file to set up the parameter tuning interface. All GUI elements are
# populated based on this file. This example is written as if it was for use with ROSplane.
#
# {Name of parameter group}:
#   node: '/{ROS_node_name}'
#   params:
#     {param_name}:
#       description: '{Parameter Description}'
#       scale: {Scale Factor to use with parameters}  (optional, default is 1.0)
#     ...
#   plot_axis_label: '{Y Axis Label}'  (x axis is always 'Time (s)')
#   plot_topics: (optional, include if you want to plot data)
#     {Plot Name}: '/{ROS_topic_name}/{field_name}'
#     ...
# ...


Roll Angle:
  node: '/autopilot'
  params:
    r_kp:
      description: 'Roll angle P gain'
    r_kd:
      description: 'Roll angle D gain'
  plot_axis_label: 'Roll angle (deg)'
  plot_topics:
    Roll Command: '/controller_internals/phi_c'
    Roll Estimate: '/estimated_state/phi'

Pitch Angle:
  node: '/autopilot'
  params:
    p_kp:
      description: 'Pitch angle P gain'
    p_kd:
      description:  'Pitch angle D gain'
  plot_axis_label: 'Pitch angle (deg)'
  plot_topics:
    Pitch Command: '/controller_internals/theta_c'
    Pitch Estimate: '/estimated_state/theta'

Airspeed:
  node: '/autopilot'
  params:
    a_t_kp:
      description:  'Airspeed P gain'
    a_t_ki:
      description:  'Airspeed I gain'
  plot_axis_label: 'Airspeed (m/s)'
  plot_topics:
    Airspeed Command: '/controller_command/va_c'
    Airspeed Estimate: '/estimated_state/va'

Course:
  node: '/autopilot'
  params:
    c_kp:
      description:  'Course P gain'
    c_ki:
      description: 'Course I gain'
  plot_axis_label: 'Course (deg)'
  plot_topics:
    Course Command: '/controller_command/chi_c'
    Course Estimate: '/estimated_state/chi'

Altitude:
  node: '/autopilot'
  params:
    a_kp:
      description:  'Altitude P gain'
    a_ki:
      description: 'Altitude I gain'
  plot_axis_label: 'Altitude (m)'
  plot_topics:
    Altitude Command: '/controller_command/h_c'
    Altitude Estimate: '/estimated_state/position[2]'

Line Following:
  node: '/path_follower'
  params:
    k_path:
      description:  'Line following K gain'
    chi_infty:
      description:  'Max approach angle (deg)'
      scale: 57.2957795131

Orbit Following:
  node: '/path_follower'
  params:
    k_orbit:
      description:  'Orbit following K gain'
