# Example configuration file to set up the parameter tuning interface. All GUI elements are
# populated based on this file. This example is written as if it was for use with ROSplane.
#
# {Name of parameter group}:
#   node: '/{ROS_node_name}'
#   params:
#     {param_name}:
#       description: '{Parameter description}'
#       scale: {Scale factor to use with parameters}  (optional, default is 1.0)
#     ...
#   plot_topics: (optional, include if you want to plot data)
#     {Plot name}:
#       topic: '/{ROS_topic_name}/{field_name}'
#       scale: {Scale factor to use with data}  (optional, default is 1.0)
#     ...
#   plot_axis_label: '{Y Axis Label}'  (x axis is always 'Time (s)')
# ...


Roll Angle:
  node: '/autopilot'
  params:
    r_kp:
      description: 'Roll angle P gain'
    r_kd:
      description: 'Roll angle D gain'
  plot_topics:
    Roll Command:
      topic: '/controller_internals/phi_c'
      scale: 57.2957795131
    Roll Estimate:
      topic: '/estimated_state/phi'
      scale: 57.2957795131
  plot_axis_label: 'Roll angle (deg)'

Pitch Angle:
  node: '/autopilot'
  params:
    p_kp:
      description: 'Pitch angle P gain'
    p_kd:
      description:  'Pitch angle D gain'
  plot_topics:
    Pitch Command:
      topic: '/controller_internals/theta_c'
      scale: 57.2957795131
    Pitch Estimate:
      topic: '/estimated_state/theta'
      scale: 57.2957795131
  plot_axis_label: 'Pitch angle (deg)'

Airspeed:
  node: '/autopilot'
  params:
    a_t_kp:
      description:  'Airspeed P gain'
    a_t_ki:
      description:  'Airspeed I gain'
  plot_topics:
    Airspeed Command:
      topic: '/controller_command/va_c'
    Airspeed Estimate:
      topic: '/estimated_state/va'
  plot_axis_label: 'Airspeed (m/s)'

Course:
  node: '/autopilot'
  params:
    c_kp:
      description:  'Course P gain'
    c_ki:
      description: 'Course I gain'
  plot_topics:
    Course Command:
      topic: '/controller_command/chi_c'
      scale: 57.2957795131
    Course Estimate:
      topic: '/estimated_state/chi'
      scale: 57.2957795131
  plot_axis_label: 'Course (deg)'

Altitude:
  node: '/autopilot'
  params:
    a_kp:
      description:  'Altitude P gain'
    a_ki:
      description: 'Altitude I gain'
  plot_topics:
    Altitude Command:
      topic: '/controller_command/h_c'
    Altitude Estimate:
      topic: '/estimated_state/position[2]'
      scale: -1.0
  plot_axis_label: 'Altitude (m)'

Line Following:
  node: '/path_follower'
  params:
    k_path:
      description:  'Line following K gain'
    chi_infty:
      description:  'Max approach angle (deg)'
      scale: 57.2957795131

Orbit Following:
  node: '/path_follower'
  params:
    k_orbit:
      description:  'Orbit following K gain'
